-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "todoapp"."todos" ADD "isCompleted" bit NOT NULL CONSTRAINT "default_sqlserverdb_todoapp_todos_isCompleted" DEFAULT '0' WITH VALUES;
