-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "todoapp"."todos" ADD "stamp" date NOT NULL CONSTRAINT "default_sqlserverdb_todoapp_todos_stamp" DEFAULT 'GETDATE()' WITH VALUES;
